### ISSUE TITLE
[Bug] Crash when apply connecting glass pane to copycat panel from create

### ISSUE THREAD

**Issue by zTrap** [SuperMartijn642/ConnectedGlass#43]
**Version Info**
- Minecraft, 1.20.1
- Connected Glass, 1.1.7
- Create, 0.5.1-d-build.1161+mc1.20.1

**Mod loader**
- Fabric

**Description of the Bug**
- Game crashing after applying connecting glass pane to Create's copycat panel and world become unaccessible untill you remove connected glass from mods folder and then enter the world. But it works fine when you apply connecting glass. 

**Steps to Reproduce**
- Launch minecraft with `Connected Glass 1.1.7` and `Create 0.5.1-d-build.1161+mc1.20.1`
- Create world
- Place Create's Copycat panel somewhere with any direction
- Apply any Connecting glass pane to Copycat panel

<details>
  <summary><b>Stacktrace</b></summary>
<pre>
-- Head --
Thread: Render thread
Stacktrace:
java.lang.IllegalArgumentException: Cannot get property class_2746{name=north, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{create:copycat_panel}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.minecraft.class_818.method_3528(class_818.java:62)
	at net.minecraft.class_1095.method_4707(class_1095.java:56)
	at com.supermartijn642.connectedglass.model.CGBakedModel.method_4707(CGBakedModel.java:69)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractBlockRenderContext$BakedModelConsumerImpl.accept(AbstractBlockRenderContext.java:305)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractBlockRenderContext$BakedModelConsumerImpl.accept(AbstractBlockRenderContext.java:295)
	at com.supermartijn642.connectedglass.model.CGBakedModel.emitBlockQuads(CGBakedModel.java:49)
	at com.simibubi.create.content.decoration.copycat.CopycatBarsModel.emitBlockQuadsInner(CopycatBarsModel.java:51)
	at com.simibubi.create.content.decoration.copycat.CopycatPanelModel.emitBlockQuadsInner(CopycatPanelModel.java:57)
	at com.simibubi.create.content.decoration.copycat.CopycatModel.emitBlockQuads(CopycatModel.java:72)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)
	at net.minecraft.class_846$class_851$class_4578.redirect$bab000$fabric-renderer-indigo$hookChunkBuildTessellate(class_846.java:783)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:579)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:490)
</pre>

<pre>
-- Block being tessellated --
Details:
	Block: Block{create:copycat_panel}[facing=north,waterlogged=false]
	Block location: World: (1299,74,-3863), Section: (at 3,10,9 in 81,4,-242; chunk contains blocks 1296,-64,-3872 to 1311,319,-3857), Region: (2,-8; contains chunks 64,-256 to 95,-225, blocks 1024,-64,-4096 to 1535,319,-3585)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)
	at net.minecraft.class_846$class_851$class_4578.redirect$bab000$fabric-renderer-indigo$hookChunkBuildTessellate(class_846.java:783)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:579)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:490)
	at net.minecraft.class_846.method_22757(class_846.java:141)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
</pre>
</details>

**Comment by SuperMartijn642** [comment]
The crash should be fixed now in Connected Glass version 1.1.8. It still looks horrible when actually putting a glass pane in the copycat blocks, but it is the same for the vanilla glass panes, so 🤷‍♂️

Thank you for reporting the issue!
