### ISSUE TITLE
[Bug] Fusion is a necessary dependency for the server

### ISSUE THREAD

**Issue by noahreinalter** [SuperMartijn642/ConnectedGlass#50]
**Version Info**
- Minecraft, 1.20.1
- Fabric, 0.14.24
- Connected Glass, 1.1.9

**Description of the Bug**
The new version of Connected Glass adds Fusion as a necessary dependency even for the server where Fusion doesn't do anything

**Steps to Reproduce**
Don't install Fusion on a Fabric server but Connected Glass and SuperMartijn642's Core Lib

**More details**
	 - Mod 'Connected Glass' (connectedglass) 1.1.9 requires version 1.1.0 or later of fusion, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]

**Comment by SuperMartijn642** [comment]
Fabric does not have a way to add a dependency for one side only. I can add a dependency for either both the server and the client, or for neither. In this case, I'd rather have an unnecessary dependency on the server than have it not work for people because they are missing the dependency on the client.

Sadly, that's just a limitation of Fabric Loader. For now, there's no harm in adding Fusion to the server as well, it just won't do anything.

**Comment by noahreinalter** [comment]
Thanks for the quick reply. Sad that that is not possible with Fabric
